# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_scholes.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62lack_scholes.proto\x12\x0f\x66inance.options\"\xd2\x01\n\x16\x42lackScholesParameters\x12\x13\n\x0bstock_price\x18\x01 \x01(\x01\x12\x14\n\x0cstrike_price\x18\x02 \x01(\x01\x12\x16\n\x0erisk_free_rate\x18\x03 \x01(\x01\x12\x15\n\rdividend_rate\x18\x04 \x01(\x01\x12\x12\n\nvolatility\x18\x05 \x01(\x01\x12\x18\n\x10time_to_maturity\x18\x06 \x01(\x01\x12\x30\n\x0boption_type\x18\x07 \x01(\x0e\x32\x1b.finance.options.OptionType\"S\n\x14OptionPricingRequest\x12;\n\nparameters\x18\x01 \x01(\x0b\x32\'.finance.options.BlackScholesParameters\"\x8b\x01\n\x15OptionPricingResponse\x12\x14\n\x0coption_price\x18\x01 \x01(\x01\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\x01\x12\r\n\x05gamma\x18\x03 \x01(\x01\x12\x0c\n\x04vega\x18\x04 \x01(\x01\x12\x30\n\x0boption_type\x18\x05 \x01(\x0e\x32\x1b.finance.options.OptionType*\x1f\n\nOptionType\x12\x08\n\x04\x43\x41LL\x10\x00\x12\x07\n\x03PUT\x10\x01\x32\x7f\n\x14OptionPricingService\x12g\n\x14\x43\x61lculateOptionPrice\x12%.finance.options.OptionPricingRequest\x1a&.finance.options.OptionPricingResponse\"\x00\x42H\n\x0f\x66inance.optionsB\x12OptionPricingProtoZ\x0f\x66inance/options\xaa\x02\x0f\x46inance.Optionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'black_scholes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017finance.optionsB\022OptionPricingProtoZ\017finance/options\252\002\017Finance.Options'
  _globals['_OPTIONTYPE']._serialized_start=480
  _globals['_OPTIONTYPE']._serialized_end=511
  _globals['_BLACKSCHOLESPARAMETERS']._serialized_start=41
  _globals['_BLACKSCHOLESPARAMETERS']._serialized_end=251
  _globals['_OPTIONPRICINGREQUEST']._serialized_start=253
  _globals['_OPTIONPRICINGREQUEST']._serialized_end=336
  _globals['_OPTIONPRICINGRESPONSE']._serialized_start=339
  _globals['_OPTIONPRICINGRESPONSE']._serialized_end=478
  _globals['_OPTIONPRICINGSERVICE']._serialized_start=513
  _globals['_OPTIONPRICINGSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
