# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import black_scholes_pb2 as black__scholes__pb2


class OptionPricingServiceStub(object):
    """Service definition for option pricing
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateOptionPrice = channel.unary_unary(
                '/finance.options.OptionPricingService/CalculateOptionPrice',
                request_serializer=black__scholes__pb2.OptionPricingRequest.SerializeToString,
                response_deserializer=black__scholes__pb2.OptionPricingResponse.FromString,
                )


class OptionPricingServiceServicer(object):
    """Service definition for option pricing
    """

    def CalculateOptionPrice(self, request, context):
        """Calculates the price of an option using Black-Scholes model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptionPricingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateOptionPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateOptionPrice,
                    request_deserializer=black__scholes__pb2.OptionPricingRequest.FromString,
                    response_serializer=black__scholes__pb2.OptionPricingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finance.options.OptionPricingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OptionPricingService(object):
    """Service definition for option pricing
    """

    @staticmethod
    def CalculateOptionPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/finance.options.OptionPricingService/CalculateOptionPrice',
            black__scholes__pb2.OptionPricingRequest.SerializeToString,
            black__scholes__pb2.OptionPricingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
